# Generated by Django 4.0.3 on 2022-03-11 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_std'),
    ]

    operations = [
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='std',
        ),
    ]
