# Generated by Django 4.0.3 on 2022-03-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_std_c_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='std',
            name='c_id',
            field=models.CharField(max_length=55),
        ),
    ]
