# Generated by Django 4.0.3 on 2022-03-11 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_alter_std_c_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='std',
            old_name='c_id',
            new_name='c_name',
        ),
    ]
